# Install Python dependencies, format and lint with a single version of Python.

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pytest ruff
    - name: Check with ruff
      run: ruff check --output-format=github .
    - name: Format with ruff
      run: ruff format .
    - name: Test with pytest
      run: pytest
